server:
  port: 8555
spring:
  cloud:
    client:
      hostname: localhost
  application:
    name: auth-service
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: ${DB_USERS_URL}
    username: ${DB_USERS_USER}
    password: ${DB_USERS_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: password


springdoc:
  api-docs:
    path: /authentication-docs
  swagger-ui:
    path: /authentication-docs/swagger-ui-custom.html

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
