version: '3.8'

services:
  usersdb:
    image: postgres:latest
    container_name: usersdb
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - usersdb-data:/var/lib/postgresql/data

  redis-cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password

volumes:
  usersdb-data:
