spring:
  application:
    name: gateway
  cloud:
    client:
      hostname: localhost

server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
