spring:
  application:
    name: gateway
  cloud:
    client:
      hostname: localhost

    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/login,/api/auth/signup

  main:
    web-application-type: reactive

server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
