server:
  port: ${PORT:0}
spring:
  cloud:
    client:
      hostname: localhost
  application:
    name: appointments-service
  datasource:
    url: ${DB_USERS_URL}
    username: ${DB_USERS_USER}
    password: ${DB_USERS_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
      password: password

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

